version: '3.5'

services:
  spotifree-gateway:
    image: spotifree-gateway:latest
    container_name: spotifree-gateway
    build:
      context: ./src/services/Gateway
      dockerfile: Dockerfile
    ports:
      - "22000:80"

  spotifree-authservice:
    image: spotifree-authservice:latest
    container_name: spotifree-authservice
    build:
      context: ./src/services/AuthService
      dockerfile: Dockerfile
    ports:
      - "51010:80"
    depends_on:
      - spotifree-rabbitmq
    restart: on-failure
    environment:
      SPOTIFREE_RABBITMQ: '{"UserName": "guest","Password": "guest","HostName": "spotifree-rabbitmq","VHost": "/","Port": 5672}'

  spotifree-userservice:
    image: spotifree-userservice:latest
    container_name: spotifree-userservice
    build:
      context: ./src/services/UserService
      dockerfile: Dockerfile
    ports:
      - "51020:80"
    depends_on:
      - spotifree-rabbitmq
    environment:
      SPOTIFREE_USERSERVICE_DB: 'Server=tcp:fdemirci.tplinkdns.com,1433;Initial Catalog=UserDatabase;Persist Security Info=False;User ID=spotifree;Password=543532;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=False;Connection Timeout=30;'
      SPOTIFREE_RABBITMQ: '{"UserName": "guest","Password": "guest","HostName": "spotifree-rabbitmq","VHost": "/","Port": 5672}'

  spotifree-rabbitmq:
    image: rabbitmq:3-management
    container_name: spotifree-rabbitmq
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5